//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bsi24tallerbilly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public long idComment { get; set; }
        public string Username { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string Tema { get; set; }
    }
}
